### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by JamesRamm** [JamesRamm/MapPIG#27]
@RonKalian @yitang

'MapThing' is a fairly vague and nondescript name...would a change be more suitable?

All I have come up with is MapVis, which is a little more specific....

**Comment by JamesRamm** [comment]
MapVis
VMap
GeoVi
GISPig
Are some names that have been suggested....

**Comment by JamesRamm** [comment]
And Platform for Interaction with Geospatial Data or Pigd

**Comment by mdsumner** [comment]
VisPIG ?  I do like the "probably isn't . . ." description and this resonates with the "Platform . . ." initialism.

**Comment by RonKalian** [comment]
On choice of name it would depend on who or what you are targeting it at.  The name should also make it clear what it is, and work for GitHub searches (so that GIS, Maps, catModelling all hit it).  It definitely is based on mapping, and the extensions can be used to integrate with other systems (using web services or other integration patterns).  So I'd keep 'map' in the name... I don't think 'vis' adds anything, it is obvious that maps are visual.  How's about **MapPIG**?  The PIG can give a slight negetive connotation, but then there's nothing wrong with a bit of humour to stand out from the crowd and make the name memorable ... see the  example of 'git' (as a name for an open source project).

**Comment by JamesRamm** [comment]
I'm leaning toward MapPIG as it fits the (contrived) acronymn a bit better than VisPIG:

Mapping Platform for Interaction with Geodata

It also rolls off my tongue a bit easier...

**Comment by mdsumner** [comment]
For what it's worth, I approve :)  I'm sure all map pigs will agree, and it's also just one letter from "mapping" which is cool.  I'm excited to use it, I got it going on a vm but it's still at the edge of my capabilities, hoping to learn more soon!

**Comment by JamesRamm** [comment]
Ok, then we will go with MapPIG. 

Its' still at the edge of its' own capabilities :D - there is a lot of work to do before even a 0.1 release I think!

**Comment by JamesRamm** [comment]
Be warned -Changing the name will change the github and git clone URL's.
I will make the change around 5 hours from now

**Comment by RonKalian** [comment]
Sorry for nitpicking but IMHO it should be MapPIG as PIG is an acronym.
